version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 100
      runas: ubuntu